### ISSUE TITLE
hi there I was just wondering something

### ISSUE THREAD

**Issue by AgentCube** [yell0wsuit/chrome-dino-enhanced#2]
Hi I am fairly new to web development and I am trying to make my own game website I was just wondering how you get your games on your website and where you get them from like if you use inspect or something please let me know as this would be very helpful Thanks!

**Comment by yell0wsuit** [comment]
I think it's best to watch some Youtube tutorials about this rather than asking here. I don't have intention of telling how I have done that because I don't feel like to, sorry.
I may resort to blocking you if you ignore that and keep on asking though :).
