### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by AgentCube** [yell0wsuit/chrome-dino-enhanced#4]
I am terribly sorry for doing it again when you asked me not to. I understand what you said and I did look for a video but could not find one if you could please link one that would be helpful. Again really sorry and if you don't want to link one you can just close this issue and just block me.

**Comment by yell0wsuit** [comment]
How to use the inspector tool in the browser: https://www.google.com/search?q=inspector+tool+youtube

A simple Google search would've helped you save time.

I would like to help you more, but you already have a website which has .ml domain, and from the look of it, it shows that you are quite experienced with "web development", which [contradicts to your statement on this issue](https://github.com/yell0wsuit/chrome-dino-enhanced/issues/2):
> Hi I am fairly new to web development and I am trying to make my own game website

You're not new to web development. You're just trying to learn how I get the games. Sorry, but that's a secret.

**Comment by AgentCube** [comment]
I am actually new to web development well not too much anymore as I have learned a lot but the .ml domain was a tutorial I found on youtube. I wasn't asking about how you use inspector tool I think everyone knows how to do that and yes I am was asking how you get your games not to steal them from your website but other games from other sites like poki something and if it's a secret then that's fine this was just to correct you.
