### ISSUE TITLE
Dino cannot be loaded because DOM storage is disable

### ISSUE THREAD

**Issue by hushenghao** [yell0wsuit/chrome-dino-enhanced#5]
Android system WebView must enable DOM Storage.

```java
// The default value is false.
webView.getSettings().setDomStorageEnabled(true);
```
Otherwise, it cannot be loaded.
This exception should be handled

**Comment by yell0wsuit** [comment]
What browser did you use to test this? I wasn't able to reproduce the bug on my end. ([I tried this one](https://play.google.com/store/apps/details?id=cz.lsrom.webviewtest&hl=en&gl=US))

**Comment by hushenghao** [comment]
This is not a matter of replicating in android browser apps, I'm adding the page to my application and running it offline in the WebView.
I can provide my debug log, The display problem occurs in the API of 'window.localStorage'.
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/28776451/213599091-1990ceb3-a6bd-4d01-b227-68b810018c7e.png">

-----
This is the doc for Android WebView.
```java
   // android.webkit.WebSettings#setDomStorageEnabled
   /**
     * Sets whether the DOM storage API is enabled. The default value is {@code false}.
     *
     * @param flag {@code true} if the WebView should use the DOM storage API
     */
    public abstract void setDomStorageEnabled(boolean flag);
```

**Comment by yell0wsuit** [comment]
It seems like the mentioned code is only applicable for Java app/code, I think you need to define it in your app. Chrome Dino is an HTML5 app, which is different (Java != JavaScript).

``localStorage`` is a native API in every browser by the way.

**Comment by hushenghao** [comment]
If you're only going to run it in a browser, you can forget about this.

I'm just saying 'localStorage' has some limitations in custom browsers.
